version: "2"
services:
  fb_like_backend:
    container_name: fb_like_backend
    restart: always
    build: ./server/
    command: "npm start"
    volumes:
      - "./server:/src/"  
      - /src/node_modules  
    ports:
      - "8000:8000"
  fb_like_front:
    container_name: fb_like_front
    restart: always
    build: ./client/
    stdin_open: true
    command: "npm start"
    volumes:    
      - "./app/node_modules"  
      - "./client:/app/"  
    ports:
      - "3000:3000"