export const CREATE_POST = "CREATE_POST";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";
export const GET_ALL_POSTS = "GET_ALL_POSTS";
export const GET_ALL_POSTS_FAIL = "GET_ALL_POSTS_FAIL";
export const UPDATE_POST = "UPDATE_POST";
export const UPDATE_POST_FAIL = "UPDATE_POST_FAIL";
export const DELETE_POST = "DELETE_POST";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";


